### ISSUE TITLE
WebUI - Potentially Redundant Code

### ISSUE THREAD

**Issue by nickskliar-davies** [onebeyond/onebeyond-studio-obelisk#6]
There is some potentially redundant code - someone should go through and check.

`src/OneBeyondStudio.Obelisk.WebUI/src/js/grids/syncfusionGrid/commonDataAccessors.ts`

Seems like an initial candidate.

**Comment by andriikaplanovskyi** [comment]
@nickskliar-davies @fabiomaistro WebUI project moved into another repository. Shall we close this issue?

**Comment by nickskliar-davies** [comment]
Yup - I'm happy to close this one.
