### ISSUE TITLE
DCSL Mentioned

### ISSUE THREAD

**Issue by nickskliar-davies** [onebeyond/onebeyond-studio-obelisk#7]
Lots of the code is still in `dcslcomponents` and refers to `DCSL` everywhere.

**Comment by andriikaplanovskyi** [comment]
@nickskliar-davies @fabiomaistro guys, I think we can close this issue as all UI pieces are now removed from WebAPI. Nick, can you please confirm if this is still an issue?

**Comment by nickskliar-davies** [comment]
Yup - also happy to close.
